_commit: v0.7.10
_src_path: gh:Netbeheer-Nederland/tmpl-dp
description: Information models for the NBNL Equipment data product.
name: dp-nbnl-equipment
org: Netbeheer-Nederland
schema_base_uri: http://data.netbeheernederland.nl/data-product
title: NBNL Equipment
